### ISSUE TITLE
第一帖

### ISSUE THREAD

**Issue by RGSS3** [gitrpg/GitRPG#1]
大家好

**Comment by VIPArcher** [comment]
大号好

**Comment by hyrious** [comment]
大号好

**Comment by Riajyuu** [comment]
这到底是干啥的。。。。

**Comment by RGSS3** [comment]
@Rictusempra  简单当一个交流论坛用

**Comment by hyrious** [comment]
@Rictusempra [6r今天倒闭了吗](http://rm.66rpg.com/forum.php?mod=viewthread&tid=402724)

**Comment by VIPArcher** [comment]
@hyrious 今天还没

**Comment by Riajyuu** [comment]
等等 你们是想把 GitHub 当6R用？

**Comment by congwsbn** [comment]
各位好0-0

**Comment by RGSS3** [comment]
如果某条消息造成了打扰，可以在右边关闭通知
![image](https://user-images.githubusercontent.com/4011940/30113853-a43bf682-9348-11e7-8c46-943f496ec4c7.png)

**Comment by devilib** [comment]
纯水

**Comment by kaladasa** [comment]
大清不能亡，我为RM续一秒
苟利RM生死以 岂因关停避趋之

**Comment by LanzaSchneider** [comment]
兰拯救全世界

**Comment by sherylynn** [comment]
然而这回6r要倒了

**Comment by kaladasa** [comment]
![Uploading timg.jpg…]()

**Comment by kaladasa** [comment]
![timg](https://user-images.githubusercontent.com/31718536/30196505-d039dbd6-9493-11e7-9da0-57fa0e2351d2.jpg)

**Comment by kaladasa** [comment]
![tim 20170908124803](https://user-images.githubusercontent.com/31718536/30196539-03841e8e-9494-11e7-94df-f18c9e8642ff.jpg)
![tim 20170908124807](https://user-images.githubusercontent.com/31718536/30196540-03aca110-9494-11e7-85d2-d2ce234bf32d.jpg)

**Comment by ProbeSS** [comment]
可以的 楼上很清真（
