### ISSUE TITLE
バカです

### ISSUE THREAD

**Issue by BakaSoniji** [gitrpg/GitRPG#11]
这里是笨蛋索尼子，以前又称音速君。おはようございにゃんすー
Zzz

**Comment by RGSS3** [comment]
:clap: :six:  :smile: 欢迎
我是美工，苦逼的美工
美工工具： 桂棹兮兰桨  
美工情怀：击空明兮溯流光
美工节奏： 渺渺兮余怀  
美工理想： （画）望美人兮天一方
