### ISSUE TITLE
功能测试说明

### ISSUE THREAD

**Issue by RGSS3** [gitrpg/GitRPG#2]
随便测试markdown和其他功能，
截图可以直接粘贴
![image](https://user-images.githubusercontent.com/4011940/30106911-a642089a-932f-11e7-9033-c3c79b8133b0.png)

```ruby
puts "Hello world"
@hyrious = 0 #不会自动at
```

标签只能从现有的添加，新建标签走https://github.com/RGSS3/GitRPG/labels
，可能需要权限

支持下列文件类型的拖放或者直接粘贴，或者选择下面的selecting them
![image](https://user-images.githubusercontent.com/4011940/30111956-3d2535a4-9342-11e7-88cd-f59a036ecc70.png)

签名档请自行保存为reply模板

可以在右边选Projects作为粗分类[类似于选大板块，但一个issue可以属于多个Project]，由管理员在Projects页面细分

[文档.docx](https://github.com/RGSS3/GitRPG/files/1281337/default.docx)

表情符号见https://www.webpagefx.com/tools/emoji-cheat-sheet/
:chicken:
:joy:
:six: :six: :six:

**Comment by esphas** [comment]
![image](https://user-images.githubusercontent.com/12829836/30144530-4caf080c-93be-11e7-9702-a0a7bb6eb35a.png)
甚至评分系统也有了

**Comment by RGSS3** [comment]
:six: :six: :six: :joy:
