### ISSUE TITLE
喵喵喵做个ghpages当前端吧

### ISSUE THREAD

**Issue by RGSS3** [gitrpg/GitRPG#3]
RT

**Comment by fux4** [comment]
喵喵喵女装高亮还行

**Comment by RGSS3** [comment]
@fux4 是自定义标签

**Comment by esphas** [comment]
> 用户视角：
> 1. open rgss3.github.io/GitRPG, redirect to **github auth** if not authed
> 2. 板块 = Projects
>    帖子 = Issues
>    发帖 = new issue
>    回帖 = comment on issue
>    结帖 = close issue

我觉得放这里比较好

**Comment by garfeng** [comment]
这类范例：
http://www.diyrpg.net/ (猜测是）

我自己这几天写了个范例：https://garfeng.github.io/static_site/


可以做一个ghpages，把过往数据导出为json（节省流量），ajax纯静态浏览。json存储在腾讯云/七牛云的对象存储上，以加快国内访问速度，免费额度应该够用。
搜索功能用algolia的免费版本。（无法使用谷歌自定义搜索，因为谷歌爬虫应该不爬ajax数据）

腾讯云的免费额度大概是50G存储（之前瞎，看成了10G），每月10G流量：https://www.qcloud.com/document/product/436/6240

七牛云不支持免费的https，所以大概没法使用。


# 一些不知道是否靠谱的估算：

除post/blog表，其他表都算冗余，可以砍。

对于post表，除发布用户，正文，日期，thread_id，板块id外其他都算冗余，可以砍。

对于blog表（很多人发布脚本发布在个人空间），除发布用户，正文，日期外，其他都可以砍.

----

## 存储空间（存文字数据应该是足够的）

post表我昨天看，id在270W左右，也就是2.7M的条目，假设每条占1K（300汉字），则总共是2.7G的数据。
因为大多数post都是短小的回帖，所以平均1K应该差不多。

blog表大概2W个条目，假设每条10K（3000汉字），则总共200M数据。

这样估计的数据在3G左右，存储免费额度应该够用。

----

## 请求次数：

每月110W次免费访问额度，日均3.6W的额度……这个不知道够不够。

----

## 流量：

每月10G流量，假设每次请求10K（只有json），则流量共支持100W次访问，和请求次数差不多。


注意，如果遭受流量攻击，可能使费用剧增……


如果多少有些预算，可以考虑：https://sg.godaddy.com/zh/hosting/web-hosting 旗舰版，不记存储和流量（抱歉之前看错了，感谢群里的朋友指出），月付100左右，可以保留图片，但肯定会有其他不清楚的限制。（最低配100G存储）

或者：https://www.linode.com/pricing#all Linode4GB，48G硬盘，月付150左右，只能存文本。

这两家都非常非常靠谱，都是做了很多年的服务器提供商，其中第一个说是世界上最大的域名服务器提供商应该不为过。


# 优势和可能有的风险

1. 按量付费（比如对象存储）：无需自己维护服务器，服务器始终运行良好，但如果遭遇攻击，流量蹭蹭上涨，一夜过去，房子搞不好都成了服务器提供商的。

2. 自己租用（虚拟）主机、vps：超量时一般是发邮件提醒提高配置。需要自己维护，搭建环境。如果遭遇攻击，服务器宕机，会无法访问，如果资源消耗实在太大（比如一直接近允许的峰值，但就是不提高配置），会被服务器提供商拉黑名单。

----

低价而高配的东西不存在。
只能是在能完成需求的情况下，选一个最低价的。

**Comment by RGSS3** [comment]
@fux4 #3
