### ISSUE TITLE
RM和6R有关联络方式

### ISSUE THREAD

**Issue by RGSS3** [gitrpg/GitRPG#4]
梦想世界QQ群(6R主要): 4910970
GITRPG的gitter: https://gitter.im/GitRPG/Lobby 
telegram: https://t.me/joinchat/Clk6RQbQA24mOjXQx1DGSg

润大（上贺茂润）QQ群：
VA区：113622890
MV区：377293241
XP区：427070505

索尼子的URPGs Code Alliance：
59845920

其他有关群组等联系方式，联系管理员或者回复添加:

**Comment by Riajyuu** [comment]
没有TG 差评

**Comment by RGSS3** [comment]
@taroxd 来个TG吧

**Comment by hyrious** [comment]
@Rictusempra https://t.me/joinchat/Clk6RQbQA24mOjXQx1DGSg
