### ISSUE TITLE
凑个热闹

### ISSUE THREAD

**Issue by Nothentai** [gitrpg/GitRPG#7]
_(:з」∠)_

**Comment by RGSS3** [comment]
欢迎

我是美工，苦逼的美工
美工工具： 桂棹兮兰桨  
美工情怀：击空明兮溯流光
美工节奏： 渺渺兮余怀  
美工理想： （画）望美人兮天一方

**Comment by kaladasa** [comment]
大清不能忘 我为RM续一秒
苟利RM生死以 岂因关停避趋之
