### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by RGSS3** [gitrpg/GitRPG#8]
[`Play!这个帖子`](https://gitrpg.github.io/GitRPG/jsfiddle.html?id=8)

像这样发一个issue，注意链接即可，上面一行实际上是
```
[`Play!这个帖子`](https://gitrpg.github.io/GitRPG/jsfiddle.html?id=8)
```
说明文字随便写，
假装这是注释
HTML:
```html
<H1>Hello world</H1>
```
反正我只识别代码框
JS:
```js
console.log("Hello world")
```

CSS:
```css
body{
  background: #EEE;
}
```

**Comment by RGSS3** [comment]
@taroxd @hyrious  @esphas 这就是让喵喵要写的各种外设之类的

**Comment by sxysxy** [comment]
```ruby
play this thread.
```

**Comment by RGSS3** [comment]
ruby不行 而且我只play顶楼 你可以另外发个帖试试
你可以写个play ruby的

**Comment by hyrious** [comment]
ruby 你用 glot.io 呗 )

**Comment by ghost** [comment]
Hello,World!
