### ISSUE TITLE
新人报道

### ISSUE THREAD

**Issue by tamashii** [gitrpg/GitRPG#9]
我可以吞下玻璃而不伤身体
------------------------------
* 还可以这样
1. 或这样

**Comment by RGSS3** [comment]
欢迎

我是美工，苦逼的美工
美工工具： 桂棹兮兰桨  
美工情怀：击空明兮溯流光
美工节奏： 渺渺兮余怀  
美工理想： （画）望美人兮天一方

**Comment by tamashii** [comment]
话说MD用起来真舒服 -w-

**Comment by fux4** [comment]
我惊了，楼上这是谁！

**Comment by RGSS3** [comment]
我惊了，楼上这是谁！

我是美工，苦逼的美工
美工工具： 桂棹兮兰桨  
美工情怀：击空明兮溯流光
美工节奏： 渺渺兮余怀  
美工理想： （画）望美人兮天一方
